### ISSUE TITLE
symlink on windows not available

### ISSUE THREAD

**Issue by dsisnero** [wycats/bundler#137]
Downloading rack-test-0.5.3.gem
Downloading rake-0.8.7.gem
Downloading sqlite3-ruby-1.2.5.gem
Installing abstract (1.0.0)
C:/Ruby19/lib/ruby/gems/1.9.1/gems/bundler-0.7.1/lib/bundler/repository.rb:170:in `symlink': symlink() function is unimplemented on this mac
hine (NotImplementedError)
        from C:/Ruby19/lib/ruby/gems/1.9.1/gems/bundler-0.7.1/lib/bundler/repository.rb:170:in`expand_vendored_gem'
        from C:/Ruby19/lib/ruby/gems/1.9.1/gems/bundler-0.7.1/lib/bundler/repository.rb:121:in `block in do_install'
        from C:/Ruby19/lib/ruby/gems/1.9.1/gems/bundler-0.7.1/lib/bundler/repository.rb:111:in`each'
        from C:/Ruby19/lib/ruby/gems/1.9.1/gems/bundler-0.7.1/lib/bundler/repository.rb:111:in `do_install'
        from C:/Ruby19/lib/ruby/gems/1.9.1/gems/bundler-0.7.1/lib/bundler/repository.rb:44:in`install'
        from C:/Ruby19/lib/ruby/gems/1.9.1/gems/bundler-0.7.1/lib/bundler/environment.rb:60:in `install'
        from C:/Ruby19/lib/ruby/gems/1.9.1/gems/bundler-0.7.1/lib/bundler/cli.rb:39:in`bundle'
        from C:/Ruby19/lib/ruby/gems/1.9.1/gems/bundler-0.7.1/lib/bundler/cli.rb:65:in `run'
        from C:/Ruby19/lib/ruby/gems/1.9.1/gems/bundler-0.7.1/lib/bundler/cli.rb:6:in`run'
        from C:/Ruby19/lib/ruby/gems/1.9.1/gems/bundler-0.7.1/lib/bundler/commands/bundle_command.rb:68:in `execute'
        from C:/Ruby19/lib/ruby/gems/1.9.1/gems/rubygems-update-1.3.5/lib/rubygems/command.rb:257:in`invoke'
        from C:/Ruby19/lib/ruby/gems/1.9.1/gems/rubygems-update-1.3.5/lib/rubygems/command_manager.rb:132:in `process_args'
        from C:/Ruby19/lib/ruby/gems/1.9.1/gems/rubygems-update-1.3.5/lib/rubygems/command_manager.rb:102:in`run'
        from C:/Ruby19/lib/ruby/gems/1.9.1/gems/rubygems-update-1.3.5/lib/rubygems/gem_runner.rb:58:in `run'
        from C:/Ruby19/bin/gem:21:in`<main>'

**Comment by joystick** [comment]
```
def expand_vendored_gem(spec, options)
  add_spec(spec)
  FileUtils.mkdir_p(@path.join("gems"))
  if RUBY_PLATFORM.downcase =~ /[mswin|mingw]32/ 
    require 'rubygems'
    require 'win32/dir'
    Dir.create_junction(@path.join("gems", spec.full_name).to_s, spec.location.to_s)
  else
    File.symlink(spec.location, @path.join("gems", spec.full_name))
  end
end
```

**Comment by MattHulse** [comment]
Dir.create_junction looks interesting but fails on Ruby 1.9.1 so I was unable to test it.

**Comment by rubiii** [comment]
also win32/dir comes with native extensions. so it doesn't work with jruby.
