### ISSUE TITLE
wrong argument type Symbol (expected Proc)

### ISSUE THREAD

**Issue by d3ntaku** [wycats/bundler#141]
i was getting this error - maybe this is a ruby 1.8.6 issue?

[dc@tetris:dev/fish]$ gem bundle --backtrace  
ERROR:  While executing gem ... (TypeError)
    wrong argument type Symbol (expected Proc)
    /Library/Ruby/Gems/1.8/gems/bundler-0.7.2/lib/bundler/dsl.rb:110:in `gem'
    /Users/dc/dev/fish/Gemfile:8:in`evaluate'
    /Library/Ruby/Gems/1.8/gems/bundler-0.7.2/lib/bundler/dsl.rb:14:in `load_gemfile'
    /Library/Ruby/Gems/1.8/gems/bundler-0.7.2/lib/bundler/cli.rb:35:in`initialize'
    /Library/Ruby/Gems/1.8/gems/bundler-0.7.2/lib/bundler/cli.rb:6:in `new'
    /Library/Ruby/Gems/1.8/gems/bundler-0.7.2/lib/bundler/cli.rb:6:in`run'
    /Library/Ruby/Gems/1.8/gems/bundler-0.7.2/lib/bundler/commands/bundle_command.rb:68:in `execute'
    /Library/Ruby/Site/1.8/rubygems/command.rb:257:in`invoke'
    /Library/Ruby/Site/1.8/rubygems/command_manager.rb:132:in `process_args'
    /Library/Ruby/Site/1.8/rubygems/command_manager.rb:102:in`run'
    /Library/Ruby/Site/1.8/rubygems/gem_runner.rb:58:in `run'
    /usr/bin/gem:21

the following hack fixes it:

```
  # keys = %w(vendored_at path only except git path bundle require_as tag branch ref).map(&:to_sym)
  keys = [:vendored_at, :path, :only, :except, :git, :path, :bundle, :require_as, :tag, :branch, :ref]
```

**Comment by d3ntaku** [comment]
related to #134

**Comment by ukabu** [comment]
the :?to_sym construct is only available in ruby 1.9 or when using rails activesupport.

**Comment by midwire** [comment]
Thanks for the fix...  to_sym also works in 1.8.7. but I've not upgraded on a particular production box yet.
