### ISSUE TITLE
Bundler failed on Windows and Ruby 1.9.1p243 with Rails 2.3.4

### ISSUE THREAD

**Issue by deepj** [wycats/bundler#88]
Hi,
I'm trying to use Bundler in my project but I'm still getting the following error message:

<pre>
root@ROOT:/c/dev/MUNI/Bakalarka/portfonica$ ruby script/server webrick
=> Booting WEBrick
=> Rails 2.3.4 application starting on http://0.0.0.0:3000
c:/dev/MUNI/Bakalarka/portfonica/gems/environment.rb:157:in `instance_eval': can't convert Symbol into Integer (TypeError)
        from c:/dev/MUNI/Bakalarka/portfonica/gems/environment.rb:131:in `gem'
        from (eval):10:in `require_env'
        from c:/dev/MUNI/Bakalarka/portfonica/gems/environment.rb:157:in `instance_eval'
        from c:/dev/MUNI/Bakalarka/portfonica/gems/environment.rb:157:in `require_env'
        from c:/dev/MUNI/Bakalarka/portfonica/config/../config/preinitializer.rb:16:in `block (2 levels) in extend_environment'
        from c:/dev/MUNI/Bakalarka/portfonica/gems/gems/rails-2.3.4/lib/initializer.rb:137:in `process'
        from c:/dev/MUNI/Bakalarka/portfonica/gems/gems/rails-2.3.4/lib/initializer.rb:113:in `run'
        from c:/dev/MUNI/Bakalarka/portfonica/config/environment.rb:5:in `<top (required)>'
        from c:/dev/MUNI/Bakalarka/portfonica/gems/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:156:in `require'
        from c:/dev/MUNI/Bakalarka/portfonica/gems/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:156:in `block in require'
        from c:/dev/MUNI/Bakalarka/portfonica/gems/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:521:in `new_constants_in'
        from c:/dev/MUNI/Bakalarka/portfonica/gems/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:156:in `require'
        from c:/dev/MUNI/Bakalarka/portfonica/gems/gems/rails-2.3.4/lib/commands/server.rb:84:in `<top (required)>'
        from script/server:3:in `require'
        from script/server:3:in `<main>'
</pre>

I just generated a empty rails project and followed this steps:
- run <code>gem install bundle</code> command
- create a <code>Gemfile</code> in the root folder inside the empty rails project
- edit the one  (a contain of this file is below)
- create <code>config/preinitializer.rb</code> file
- put a code for this file from http://is.gd/4MmDN
- run the command gem bundle

**Gemfile**

<pre>
clear_sources
source 'http://gemcutter.org'

bundle_path 'gems'

gem 'rails',     '2.3.4'
gem 'haml',      '2.2.10'
gem 'prawn',     '0.5.1'
gem 'couchrest', '0.33'

only :test do
  gem 'rspec',       '1.2.9'
  gem 'rspec-rails', '1.2.9'
end
</pre>

Now you need to run <code>ruby script/server</code>. You should get the error message above.

I tried to use <code>disable_system_gems</code> and without one in the <code>Gemfile</code> but without any success.

**Comment by deepj** [comment]
It seems the previous error was resolved in 0.7 version.
